import { revalidateTag } from "next/cache";
import { assertSameOrigin, requireUserId } from "@/lib/social/auth";
import { socialQuery } from "@/lib/social/db";
import { socialError, socialJson, socialLimit } from "@/lib/social/http";
import { ensureSocialProfile } from "@/lib/social/profileSync";

export async function GET(request:Request,context:{params:Promise<{id:string}>}){try{const viewerId=await requireUserId(request);await ensureSocialProfile(viewerId);const {id}=await context.params;const result=await socialQuery(`select p.id,p.author_id,p.parent_id,p.content,p.image_url,p.visibility,p.likes_count,p.replies_count,p.created_at,p.updated_at,p.edited_at,json_build_object('username',s.username,'avatar_url',s.avatar_url,'level',s.level,'role',s.role,'is_premium',s.is_premium) profiles,exists(select 1 from social_post_likes l where l.post_id=p.id and l.user_id=$1) viewer_liked,exists(select 1 from social_post_bookmarks k where k.post_id=p.id and k.user_id=$1) viewer_bookmarked,(p.author_id=$1) viewer_owns from social_posts p join social_profiles s on s.user_id=p.author_id where p.id=$2 and (p.visibility='public' or p.author_id=$1 or exists(select 1 from social_follows f where f.follower_id=$1 and f.following_id=p.author_id)) and not exists(select 1 from social_blocks b where (b.blocker_id=$1 and b.blocked_id=p.author_id) or (b.blocker_id=p.author_id and b.blocked_id=$1))`,[viewerId,id]);const post=result.rows[0];if(!post)return socialJson({error:"Posting tidak tersedia."},{status:404});return socialJson({post},{headers:{"Cache-Control":"private, no-store, max-age=0"}});}catch(error){return socialError(error);}}

export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){try{assertSameOrigin(request);const userId=await requireUserId(request);if(!socialLimit(request,userId,15))return socialJson({error:"Terlalu banyak perubahan."},{status:429});const {id}=await context.params,body=await request.json() as {content?:string;visibility?:string},content=body.content?.trim().slice(0,500);if(!content)return socialJson({error:"Posting tidak boleh kosong."},{status:400});const result=await socialQuery("update social_posts set content=$3,visibility=$4,edited_at=now(),updated_at=now() where id=$1 and author_id=$2 returning id",[id,userId,content,body.visibility==="followers"?"followers":"public"]);if(!result.rowCount)return socialJson({error:"Posting tidak ditemukan."},{status:404});revalidateTag("social-posts",{expire:0});return socialJson({success:true});}catch(error){return socialError(error);}}
