"use client";
import { useCallback, useEffect, useState } from "react";
import { FiDatabase, FiRefreshCw, FiAlertCircle } from "react-icons/fi";

type Status = { database?: { database_size?: string }; counts?: { mangas?: number; chapters?: number; views?: number }; lastView?: string | null; backup?: { configured?: boolean; note?: string; latest?: { name:string; size:number; createdAt:string } | null; driveConfigured?:boolean } };
export default function ProjectDbTab({ getAdminToken }: { getAdminToken: () => Promise<string> }) {
  const [status, setStatus] = useState<Status | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const [downloading,setDownloading]=useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const token = await getAdminToken(); const res = await fetch("/api/admin/project-db/status", { headers: { Authorization: `Bearer ${token}` } }); const json = await res.json(); if (!res.ok) throw new Error(json.error || "Gagal memuat status"); setStatus(json); } catch (e) { setError(e instanceof Error ? e.message : "Gagal memuat status"); } finally { setLoading(false); } }, [getAdminToken]);
  useEffect(() => { void load(); }, [load]);
  const download=async()=>{setDownloading(true);setError("");try{const token=await getAdminToken();const res=await fetch("/api/admin/project-db/backup",{headers:{Authorization:`Bearer ${token}`}});if(!res.ok)throw new Error("Backup belum tersedia");const blob=await res.blob();const href=URL.createObjectURL(blob);const a=document.createElement("a");a.href=href;a.download=status?.backup?.latest?.name||"ryukomik_project.dump";a.click();URL.revokeObjectURL(href);}catch(e){setError(e instanceof Error?e.message:"Gagal mengunduh backup");}finally{setDownloading(false);}};
  return <section className="space-y-4"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.16em] text-emerald-300">PostgreSQL terpisah</p><h2 className="text-2xl font-black">Project Database</h2></div><button onClick={() => void load()} className="rounded-lg border border-white/10 px-3 py-2 text-xs" disabled={loading}><FiRefreshCw className={loading ? "animate-spin" : ""} /></button></div>{error && <div className="rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200"><FiAlertCircle className="mr-2 inline" />{error}</div>}{status && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Ukuran database", status.database?.database_size || "-"],["Manga", status.counts?.mangas ?? 0],["Chapter", status.counts?.chapters ?? 0],["View tercatat", status.counts?.views ?? 0]].map(([label, value]) => <div key={label} className="rounded-xl border border-white/[.08] bg-white/[.03] p-4"><p className="text-xs text-white/45">{label}</p><p className="mt-2 text-xl font-black">{value}</p></div>)}</div>}{status && <div className="rounded-xl border border-white/[.08] bg-white/[.03] p-4 text-sm"><FiDatabase className="mr-2 inline text-emerald-300" />Backup harian: <span className={status.backup?.configured ? "text-emerald-300" : "text-amber-300"}>{status.backup?.note || "Belum dikonfigurasi"}</span><p className="mt-2 text-xs text-white/45">Terbaru: {status.backup?.latest ? `${status.backup.latest.name} (${(status.backup.latest.size/1024/1024).toFixed(2)} MB)` : "belum ada"}. Google Drive: {status.backup?.driveConfigured?"aktif":"belum dikonfigurasi"}.</p><button onClick={()=>void download()} disabled={downloading||!status.backup?.latest} className="mt-3 rounded-lg bg-emerald-500 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">{downloading?"Mengunduh...":"Download backup terbaru"}</button></div>}</section>;
}
