"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { FiCheck, FiCopy, FiFolder, FiRefreshCw } from "react-icons/fi";
import { socialFetch } from "@/lib/social/client";

type Owner = { username?: string; avatar_url?: string | null };
type Collection = { id: string; name: string; description?: string | null; cover_url?: string | null; visibility: string; items_count: number; profiles?: Owner | Owner[] | null };
type Item = { source: string; slug: string; title: string; image?: string | null; created_at: string };
export default function PublicCollectionClient({ id }: { id: string }) {
  const [collection, setCollection] = useState<Collection | null>(null); const [items, setItems] = useState<Item[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [error, setError] = useState(""); const [copied, setCopied] = useState(false);
  const load = useCallback(async (more = false) => { try { const result = await socialFetch<{collection: Collection; items: Item[]; nextCursor: string | null}>(`/api/social/public-collections/${id}${more && cursor ? `?cursor=${encodeURIComponent(cursor)}` : ""}`); setCollection(result.collection); setItems((current) => more ? [...current, ...result.items] : result.items); setCursor(result.nextCursor); } catch (failure) { setError(failure instanceof Error ? failure.message : "Koleksi gagal dimuat."); } }, [cursor, id]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  async function copy() { await navigator.clipboard.writeText(window.location.href); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }
  if (error) return <div className="rk-card-soft rounded-2xl p-10 text-center text-red-200">{error}</div>;
  if (!collection) return <div className="rk-card-soft animate-pulse rounded-2xl p-16 text-center text-white/35"><FiRefreshCw className="mx-auto mb-2 animate-spin"/>Memuat koleksi...</div>;
  const owner = Array.isArray(collection.profiles) ? collection.profiles[0] || {} : collection.profiles || {};
  return <div className="space-y-5"><section className="rk-card-soft overflow-hidden rounded-3xl"><div className="relative h-40 bg-[linear-gradient(135deg,rgba(75,56,145,.8),rgba(10,61,75,.8))]">{collection.cover_url && <img src={collection.cover_url} alt="" className="h-full w-full object-cover"/>}<button onClick={copy} className="absolute right-3 top-3 grid h-10 w-10 place-items-center rounded-full bg-black/55 backdrop-blur" aria-label="Salin tautan">{copied ? <FiCheck/> : <FiCopy/>}</button></div><div className="p-5"><div className="flex items-start gap-3"><div className="grid h-11 w-11 place-items-center overflow-hidden rounded-full bg-white/5">{owner.avatar_url ? <img src={owner.avatar_url} alt="" className="h-full w-full object-cover"/> : <FiFolder/>}</div><div><h1 className="text-2xl font-black">{collection.name}</h1>{owner.username && <Link href={`/u/${encodeURIComponent(owner.username)}`} className="text-xs text-cyan-200">oleh @{owner.username}</Link>}</div></div><p className="mt-3 text-sm text-white/55">{collection.description || "Koleksi pilihan komunitas Ryukomik."}</p><p className="mt-3 text-xs text-white/35">{collection.items_count} judul · {collection.visibility === "unlisted" ? "Tautan saja" : "Publik"}</p></div></section><section className="grid grid-cols-2 gap-3 sm:grid-cols-4 md:grid-cols-5">{items.map((item) => <Link key={`${item.source}:${item.slug}`} href={`/komik/${item.source}/${item.slug}`} className="group min-w-0"><div className="aspect-[3/4] overflow-hidden rounded-xl border border-white/10 bg-white/5">{item.image ? <img src={item.image} alt="" loading="lazy" className="h-full w-full object-cover transition group-hover:scale-105"/> : <div className="grid h-full place-items-center"><FiFolder/></div>}</div><p className="mt-2 line-clamp-2 text-xs font-bold leading-snug">{item.title}</p></Link>)}</section>{cursor && <button onClick={() => load(true)} className="w-full rounded-xl border border-white/10 py-3 text-sm font-black">Muat judul lain</button>}</div>;
}
